### ISSUE TITLE
Colab pls?

### ISSUE THREAD

**Issue by Maki9009** [enhuiz/vall-e#11]
any way of having a simple colab to run this?

**Comment by faisalriazz** [comment]
I can share the sample file you can try it out. Still getting errors. Once you use configure python 3.10 , you wont be able to mount google drive.
[Copy_of_py310 (1).zip](https://github.com/enhuiz/vall-e/files/10445251/Copy_of_py310.1.zip)

**Comment by enhuiz** [comment]
I also build one that runs the toy example. Check [this link](https://colab.research.google.com/drive/1wEze0kQ0gt9B3bQmmbtbSXCoCTpq5vg-?usp=sharing).
