### ISSUE TITLE
Trainer Error  ( vall_e.train generating following errors)

### ISSUE THREAD

**Issue by faisalriazz** [enhuiz/vall-e#12]
Would you please check it our and guide me to remove this error. 

![image (4)](https://user-images.githubusercontent.com/46712242/213154952-38f19766-0c11-4bd2-ba2d-0ce88817ca4c.png)
![image (5)](https://user-images.githubusercontent.com/46712242/213154994-42250ff0-7682-45cc-b9b4-c65a5cd93fdf.png)
![image (6)](https://user-images.githubusercontent.com/46712242/213155188-e93f4570-c010-445c-a698-314ad15f38de.png)

**Comment by 0xv0idx** [comment]
lower your cuda version i had the same problem and it was fixed with cuda 11.1

**Comment by faisalriazz** [comment]
> lower your cuda version i had the same problem and it was fixed with cuda 11.1

@0xv0idx Thanks for your guidance .
