### ISSUE TITLE
How to Train Vall-e for a Singers Voice

### ISSUE THREAD

**Issue by faisalriazz** [enhuiz/vall-e#18]
@enhuiz Can you please outline a process how can we train the model for a particular singer. 
1. number of songs required ? ( Singers Vocals ) 
2. length of vocals files.
3. idean trainin parameters for ar.yml and nar.yml

**Comment by SkyYap** [comment]
Please refer to [official thesis](https://arxiv.org/abs/2301.02111). You may try it by providing several songs of the singer or plenty singers with different songs and then publish the result.

**Comment by enhuiz** [comment]
I don't know whether this work can be used for a singer's voice. I guess for the singer's voice you need to control the pitch, but the model does not take the pitch as input.
