### ISSUE TITLE
Cannot create "hello hello hello" wav file.

### ISSUE THREAD

**Issue by KiyeopYang** [enhuiz/vall-e#22]
I tried colab example as it is and I changed output text "hello world" to "hello hello hello".
But the generated wav file is not "hello hello hello" but "hello world".

How can I generate other sentence likes "hello", "world hello", "world world world"?

**Comment by lexkoro** [comment]
https://github.com/enhuiz/vall-e#get-started

> Please note that this example overfits a single utterance under the data/test and **is not usable**.
