### ISSUE TITLE
how to fine-tune model

### ISSUE THREAD

**Issue by eschmidbauer** [enhuiz/vall-e#36]
I've trained a model from scratch, the inference results are decent but I'd like to fine-tune the model further. 
I've prepared another dataset but I'm unable to resume training from the checkpoint with the new dataset. The training process still refers to the old dataset. 
Is there a way to fine-tune from an existing model?

**Comment by eschmidbauer** [comment]
figured this - you have to remember to remove the `.cache` folder is all!

**Comment by d-warfield** [comment]
@eschmidbauer Great work! Any chance you can share the model weights when you're done training? I want to fine-tune on my voice to see how it works (without having to break my GPU)
