### ISSUE TITLE
Unable to quantize the data

### ISSUE THREAD

**Issue by SkyYap** [enhuiz/vall-e#4]
After I run `python -m vall_e.emb.qnt data/your_data`, the error shown is `Error while finding module specification for 'vall_e.emb.qnt' (ModuleNotFoundError: No module named 'vall_e.emb')`

I followed the instruction by putting my data into data/sky, making the data files having 2 files (test and sky files). Audio files in data/sky is named with 1.wav and text files is named with 1.normalized.txt. I am not sure which part I am missing.

**Comment by enhuiz** [comment]
Should be fixed in b7d3c89d6d255565c1f26f7ce4000f33ace6edda, try to pull and run again.

**Comment by SkyYap** [comment]
> Should be fixed in [b7d3c89](https://github.com/enhuiz/vall-e/commit/b7d3c89d6d255565c1f26f7ce4000f33ace6edda), try to pull and run again.

Just check. You added an empty file. Is there any mistake there?

**Comment by enhuiz** [comment]
Take a look here: https://stackoverflow.com/questions/448271/what-is-init-py-for.

BTW, which Python version are you using?

**Comment by SkyYap** [comment]
I am using this [tutorial](https://www.debugpoint.com/install-python-3-10-ubuntu) to switch between Python 3.8 and Python 3.10.  I am currently using Python 3.10.7. 

```
python3 --version
Python 3.10.7
```

**Comment by SkyYap** [comment]
Worked perfectly after the update.
