### ISSUE TITLE
WorkNCCL timeout when running with torchrun

### ISSUE THREAD

**Issue by ghost** [enhuiz/vall-e#59]
![image](https://user-images.githubusercontent.com/39094983/222095848-40a36761-96c4-4e72-8242-dc3bd60f5e74.png)

**Comment by cantabile-kwok** [comment]
I also encountered this issue. The training process often stuck at some early iteration, and after a long time it raises this error. This problems insists no matter how I decrease the batch size so it should not be memory problem. Have you figured it out @primepake ?

**Comment by ghost** [comment]
Not yet! just log every step in the code!

**Comment by ghost** [comment]
solved by reduce the batch size
