### ISSUE TITLE
Issue Getting Samples

### ISSUE THREAD

**Issue by AmanKishore** [enhuiz/vall-e#6]
When running
```
python3 -m vall_e.train yaml=data/lies/ar.yml
```
I am getting the following error: 
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/vall_e/train.py", line 130, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/vall_e/train.py", line 33, in main
    train_dl, train_for_val_dl, val_dl, test_dl = create_train_val_dataloader()
  File "/usr/local/lib/python3.10/dist-packages/vall_e/data.py", line 282, in create_train_val_dataloader
    train_dl = _create_dl(train_dataset, training=True)
  File "/usr/local/lib/python3.10/dist-packages/vall_e/data.py", line 205, in _create_dl
    return DataLoader(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 344, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
```

These are the files in my `data/lies` dir:
```
ar.yml  lies.normalized.txt  lies.phn.txt  lies.qnt.pt  lies.wav  nar.yml
```

And this is my `ar.yml` file:
```
data_dirs: [data/lies]

model: ar-quarter
batch_size: 1
eval_batch_size: 1
save_ckpt_every: 500
eval_every: 500
max_iter: 1000
```

**Comment by enhuiz** [comment]
The current implementation requires at least two speeches from the same speaker. It uses one as a style prompt and the other as the content to generate. You should add another audio of the same speaker.

BTW, the code obtains speaker label based on the utterance path `p`:

 https://github.com/enhuiz/vall-e/blob/2a68378421648f4ecc7b6640a22469e716395bbb/vall_e/config.py#L42

By default, it is the name of the parent folder (i.e. `lies`).

**Comment by AmanKishore** [comment]
So here is my `data/harry`
```
ar.yml               lies.phn.txt  lies.wav            mad.phn.txt  mad.wav
lies.normalized.txt  lies.qnt.pt   mad.normalized.txt  mad.qnt.pt   nar.yml
```
What do I need to change for `ar.yml`?
```
data_dirs: [data/harry/]

model: ar-quarter
batch_size: 1
eval_batch_size: 1
save_ckpt_every: 500
eval_every: 500
max_iter: 1000
```

**Comment by 0xv0idx** [comment]
i am facing the same problem, i have produced 2 waw and normalized text also qnt.pt and phn for each but i still get the same error. "ValueError: num_samples should be a positive integer value, but got num_samples=0"

**Comment by camenduru** [comment]
not like this ? 
![Screenshot 2023-01-17 232814](https://user-images.githubusercontent.com/54370274/213005795-dd79d23f-3439-4f6b-b9d5-87d8730f0410.jpg)

**Comment by enhuiz** [comment]
The utterance might be filtered out due to 

https://github.com/enhuiz/vall-e/blob/2a68378421648f4ecc7b6640a22469e716395bbb/vall_e/config.py#L44-L45

and

https://github.com/enhuiz/vall-e/blob/2a68378421648f4ecc7b6640a22469e716395bbb/vall_e/data.py#L60-L71

What's the number of phones in both the `.phn.txt` files?

**Comment by 0xv0idx** [comment]
first .phn file
`K R IH1 S P L IY0 _ P R IH1 N T AH0 D _ D IH1 N ER0 _ M EH1 N Y UW0 Z _ T AY1 T AH0 L _ AH0 _ F IY1 S T _ AH0 _ R IY1 Z AH0 N _ P R AA1 M AH0 S T _ W IY1 _ AA1 R _ G EH1 T _ DH AH0 _ M AH1 N IY0 Z _ W ER1 TH`
second .phn file
`AH0 N D _ W IY1 _ M EY1 D _ DH AH0 _ T OW1 N _ AE1 N _ AH0 N L AY1 K L IY0 _ M AE1 CH _ AH0 _ S AH0 K S EH1 SH AH0 N _ AH1 V _ T R AE1 V AH0 L IH0 NG _ N OW1 T AH0 B AH0 L Z _ IH0 N K L UW1 D IH0 NG`

and look like this
![image](https://user-images.githubusercontent.com/12444059/213028106-debdd0f3-53d1-49a1-89d2-b4460e94bce5.png)

and error this
![image](https://user-images.githubusercontent.com/12444059/213028160-64992d88-061a-4e73-9f60-3c19fc87243d.png)

**Comment by enhuiz** [comment]
try add max_phones: 200 to you y'all

**Comment by 0xv0idx** [comment]
after trying nar its work ar file still same error

**Comment by camenduru** [comment]
how about working on this https://github.com/camenduru/vall-e-colab/blob/main/vall-e.ipynb

**Comment by camenduru** [comment]
I am also getting same error with colab

**Comment by enhuiz** [comment]
> after trying nar its work ar file still same error

The data loader is cached. Try to remove the .cache folder.

**Comment by 0xv0idx** [comment]
> > after trying nar its work ar file still same error
> 
> The data loader is cached. Try to remove the .cache folder.

yep fixed thnx

**Comment by AmanKishore** [comment]
I'm getting this error: 
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/vall_e/train.py", line 128, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/vall_e/train.py", line 33, in main
    train_dl, subtrain_dl, val_dl = create_train_val_dataloader()
  File "/usr/local/lib/python3.10/dist-packages/vall_e/data.py", line 267, in create_train_val_dataloader
    train_dataset, val_dataset = create_datasets()
  File "/usr/local/lib/python3.10/dist-packages/vall_e/data.py", line 253, in create_datasets
    val_dataset = VALLEDatset(
  File "/usr/local/lib/python3.10/dist-packages/vall_e/data.py", line 106, in __init__
    raise ValueError("No valid path is found. ")
ValueError: No valid path is found. 
```
