### ISSUE TITLE
Getting error while quantizing data

### ISSUE THREAD

**Issue by shivam017arora** [enhuiz/vall-e#63]
I downloaded Obama's speech and its transcription, and put that into the data folder. 
I used this data: https://drive.google.com/drive/folders/17mHURkxigU5cbmPkBOCWaxfaoNBn9hU0?usp=share_link

When I run the command
```
!python -m vall_e.emb.qnt data/your_data
```
I am not able to generate the other files, instead it stops running and shows me this output;
```
0it [00:00, ?it/s]
```

What could be the reason behind this? Is my data not in the correct format? PLEASE HELP!

**Comment by NomaanAhmed** [comment]
@shivam017arora what was it?
